# Generated by Django 5.1.6 on 2025-02-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_actionablestep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionablestep',
            name='actionable_step',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
