# Generated by Django 5.1.6 on 2025-02-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actionablestep_actionable_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_content', models.TextField()),
                ('reminder_date', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.actionablestep')),
            ],
        ),
    ]
