# Generated by Django 5.1.6 on 2025-02-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.patient'),
        ),
    ]
